name: CI
on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    name: build example and deploy to minikube
    steps:
      - uses: actions/checkout@v2
      - name: Start minikube
        uses: medyagh/setup-minikube@master
        with:
          start-args: '--disk-size=10g --extra-disks=1'
      - name: Try the cluster !
        run: kubectl get pods -A
      - name: Deploy to minikube
        run: |
          kubectl apply -f https://raw.githubusercontent.com/rook/rook/v1.10.11/deploy/examples/crds.yaml
          kubectl apply -f https://raw.githubusercontent.com/rook/rook/v1.10.11/deploy/examples/common.yaml
          kubectl apply -f https://raw.githubusercontent.com/rook/rook/v1.10.11/deploy/examples/operator.yaml
          kubectl apply -f https://raw.githubusercontent.com/onmetal/cephlet/main/docs/development/rook/pool.yaml
          kubectl apply -f https://raw.githubusercontent.com/onmetal/cephlet/main/docs/development/rook/cluster.yaml
      - name: Test service URLs
        run: |
          kubectl get pod -A
