name: CI
on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    name: build example and deploy to minikube
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: libvirt
        run: |
          cat /sys/module/kvm_amd/parameters/nested
          egrep -c ' lm ' /proc/cpuinfo
          sudo apt-get update
          sudo apt-get install qemu-kvm libvirt-daemon-system libvirt-clients bridge-utils
          sudo adduser `id -un` libvirt
          sudo usermod -aG kvm `id -un`
          sudo usermod -aG libvirt `id -un`    
          sudo chmod 666 /run/libvirt/libvirt-sock
          echo "options kvm_intel nested=1" >  kvm_intel.conf
          sudo cp kvm_intel.conf /etc/modprobe.d/kvm_intel.conf
          sudo lsmod
          virt-host-validate
      - name: Start minikube
        uses: medyagh/setup-minikube@master
        with:
          start-args: '--disk-size=10g --extra-disks=1 --driver kvm2'
      - name: Try the cluster !
        run: kubectl get pods -A
      - name: Deploy to minikube
        run: |
          kubectl apply -f https://raw.githubusercontent.com/rook/rook/v1.10.11/deploy/examples/crds.yaml
          kubectl apply -f https://raw.githubusercontent.com/rook/rook/v1.10.11/deploy/examples/common.yaml
          kubectl apply -f https://raw.githubusercontent.com/rook/rook/v1.10.11/deploy/examples/operator.yaml
          kubectl wait --for=condition=ready pod -n rook-ceph -l app=rook-ceph-operator
          kubectl apply -f https://raw.githubusercontent.com/onmetal/cephlet/main/docs/development/rook/cluster.yaml
          kubectl apply -f https://raw.githubusercontent.com/onmetal/cephlet/main/docs/development/rook/pool.yaml
      - name: Test service URLs
        run: |
          kubectl get pod -A
          kubectl logs -n rook-ceph -l app=rook-ceph-operator
          sleep 30
          kubectl get pod -A
          kubectl logs -n rook-ceph -l app=rook-ceph-operator
          sleep 30
          kubectl get pod -A
          kubectl logs -n rook-ceph -l app=rook-ceph-operator
          sleep 30
          kubectl get pod -A
          kubectl logs -n rook-ceph -l app=rook-ceph-operator
          sleep 30
          kubectl get pod -A 
          kubectl logs -n rook-ceph -l app=rook-ceph-operator
          kubectl describe cephblockpool -n rook-ceph cephlet-pool
          kubectl wait --for=condition=ready --timeout=30s pod -n rook-ceph -l app=rook-ceph-mon
          kubectl wait --for=condition=ready --timeout=30s cephcluster -n rook-ceph my-cluster
          kubectl get pod -A
          sleep 30   
          kubectl describe cephblockpool -n rook-ceph cephlet-pool
          sleep 30   
          kubectl describe cephblockpool -n rook-ceph cephlet-pool
          kubectl wait --for=condition=ready --timeout=30s cephblockpool -n rook-ceph cephlet-pool
          kubectl get pod -A
